// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Ixyj1eL3E3hBNofgOA0CITJmGmKBqwg',
    appId: '1:356536633587:android:15d200948a53d547048f86',
    messagingSenderId: '356536633587',
    projectId: 'fireapp-a66ac',
    storageBucket: 'fireapp-a66ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0wfbggm5uui2DFMDbeSihVhn55yDHsIg',
    appId: '1:356536633587:ios:db73907ae037ad19048f86',
    messagingSenderId: '356536633587',
    projectId: 'fireapp-a66ac',
    storageBucket: 'fireapp-a66ac.firebasestorage.app',
    androidClientId: '356536633587-qle0lpat6lodd7mo108vqkfh5hedo5s1.apps.googleusercontent.com',
    iosClientId: '356536633587-dkcihj36vnkdb6sgql2d3hau6vmdughi.apps.googleusercontent.com',
    iosBundleId: 'com.example.smokelessMovies',
  );

}